### ISSUE TITLE
Cuando se esta usando la rutal /cualquiercosa no se puede subir imagenes

### ISSUE THREAD

**Issue by kyxer** [joselfonseca/image-manager#5]
Cuando una app esta usando la ruta /cualquiercosa la ruta /image-manager no funciona

**Comment by joselfonseca** [comment]
Es un caso muy particular. tener una ruta /{foo} puede afectar cualquier otra ruta ya que en teoría cualquier cosa que sea `/foo` `/bar` `/baz` va a ser tomada por esa ruta. voy a evaluar el caso a ver si se puede hacer algo. Gracias!
