### ISSUE TITLE
May I ask whether this tool supports laravel 5.2.x?

### ISSUE THREAD

**Issue by kingasds** [joselfonseca/image-manager#6]
I have encountered following issue when uploading and deletion images. By any chance you could look into it?

I am using laravel 5.2.3 for development.

Outcome:
Upload image successfully, but the modal do not update the images in collections.
Delete image only remove the image in for the storage folder, MYSQL record remains,

Here are the error messages under debug mode:
UrlGenerationException in UrlGenerationException.php line 17:
Missing required parameters for [Route: media] [URI: image-manager/view/{id}/{width}/{height}/{canvas}].
in UrlGenerationException.php line 17
at UrlGenerationException::forMissingParameters(object(Route)) in UrlGenerator.php line 332
at UrlGenerator->toRoute(object(Route), '15', true) in UrlGenerator.php line 304
at UrlGenerator->route('media', '15', true, null) in helpers.php line 616
at route('media', '15') in ImageManagerFiles.php line 37
at ImageManagerFiles->getFileInfo() in ImageManagerController.php line 62
at ImageManagerController->store()

**Comment by kingasds** [comment]
For temporary fix, I modified route.php in vendor\joselfonseca\image-manager\src\routes.php (Line16 - 29)

From
```
Route::get('image-manager/view/{id}/{width}', [
    'as' => 'media',
    'uses' => '\\Joselfonseca\\ImageManager\\Controllers\\ImageManagerController@full'
])->where('width', '[0-9]+');

Route::get('image-manager/view/{id}/{width}/{height}', [
    'as' => 'media',
    'uses' => '\\Joselfonseca\\ImageManager\\Controllers\\ImageManagerController@full'
])->where('width', '[0-9]+')->where('height', '[0-9]+');

Route::get('image-manager/view/{id}/{width}/{height}/{canvas}', [
    'as' => 'media',
    'uses' => '\\Joselfonseca\\ImageManager\\Controllers\\ImageManagerController@full'
])->where('width', '[0-9]+')->where('height', '[0-9]+')->where('canvas', 'canvas');
```

To:
```
Route::get('image-manager/view/{id}/{width?}', [
    'as' => 'media',
    'uses' => '\\Joselfonseca\\ImageManager\\Controllers\\ImageManagerController@full'
])->where('width', '[0-9]+');

Route::get('image-manager/view/{id}/{width?}/{height?}', [
    'as' => 'media',
    'uses' => '\\Joselfonseca\\ImageManager\\Controllers\\ImageManagerController@full'
])->where('width', '[0-9]+')->where('height', '[0-9]+');

Route::get('image-manager/view/{id}/{width?}/{height?}/{canvas?}', [
    'as' => 'media',
    'uses' => '\\Joselfonseca\\ImageManager\\Controllers\\ImageManagerController@full'
])->where('width', '[0-9]+')->where('height', '[0-9]+')->where('canvas', 'canvas');
```

**Comment by joselfonseca** [comment]
Hello there, I haven't been able to look at this, but if that fixes the issue a PR would be great :)

**Comment by joselfonseca** [comment]
closed https://github.com/joselfonseca/image-manager/pull/7
