### ISSUE TITLE
Call to undefined method Illuminate\Foundation\Application::bindShared() 

### ISSUE THREAD

**Issue by Photoshopper** [joselfonseca/image-manager#8]
I can't do vendor:publish. I get an error in Laravel 5.3

```
[Symfony\Component\Debug\Exception\FatalThrowableError]                   
Call to undefined method Illuminate\Foundation\Application::bindShared()  
```

**Comment by joselfonseca** [comment]
Hello, haven't test this in 5.3, however the package will not receive updates so i recommend using this instead.

https://github.com/spatie/laravel-medialibrary

Cheers!
